// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SingleStone.Data;

namespace SingleStone.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201006181325_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("SingleStone.Models.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("SingleStone.Models.Entities.ContactAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<int>("ContactId");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("Zip");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.ToTable("ContactAddresses");
                });

            modelBuilder.Entity("SingleStone.Models.Entities.ContactName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContactId");

                    b.Property<string>("First");

                    b.Property<string>("Last");

                    b.Property<string>("Middle");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.ToTable("ContactName");
                });

            modelBuilder.Entity("SingleStone.Models.Entities.ContactPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContactId");

                    b.Property<string>("Number");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactPhone");
                });

            modelBuilder.Entity("SingleStone.Models.Entities.ContactAddress", b =>
                {
                    b.HasOne("SingleStone.Models.Entities.Contact", "Contact")
                        .WithOne("Address")
                        .HasForeignKey("SingleStone.Models.Entities.ContactAddress", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SingleStone.Models.Entities.ContactName", b =>
                {
                    b.HasOne("SingleStone.Models.Entities.Contact", "Contact")
                        .WithOne("Name")
                        .HasForeignKey("SingleStone.Models.Entities.ContactName", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SingleStone.Models.Entities.ContactPhone", b =>
                {
                    b.HasOne("SingleStone.Models.Entities.Contact", "Contact")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
